[project]
name = "simple-echo"
version = "0.0.1"
description = "Echo script"
authors = [{ name = "Cristi Pufu", email = "cristian.pufu@uipath.com" }]
dependencies = [
    "uipath_sdk>=0.0.36"
]
requires-python = ">=3.10"
