sonar.projectKey=UiPath_uipath-python
sonar.organization=ui
sonar.host.url=https://sonarcloud.io

sonar.sources=packages/uipath/src,packages/uipath-core/src,packages/uipath-platform/src
sonar.tests=packages/uipath/tests,packages/uipath-core/tests,packages/uipath-platform/tests

sonar.python.version=3.11,3.12,3.13
sonar.python.coverage.reportPaths=packages/uipath/coverage.xml,packages/uipath-core/coverage.xml,packages/uipath-platform/coverage.xml

sonar.exclusions=**/samples/**,**/testcases/**,**/template/**,**/_resources/**

sonar.sourceEncoding=UTF-8
