# .pyi files don't support runtime conditions (like checking if a package is installed).
# This file is generated by the build system. Do not edit it directly.

from typing import TYPE_CHECKING

from ._base_service import BaseService

if TYPE_CHECKING:
    # import all the connectors
    # from uipath_connectors.[NAME] import [NAME]  # type: ignore
    ...

class Connectors(BaseService):
    # All the connectors are defined here
    # [NAME]: [CONNECTOR_CLASS]
    ...
