"""CLI commands for working with agent trajectory traces.

Reads JSONL trace files (from ``uipath run --trace-file``) or eval verbose
JSON output (from ``uipath eval --verbose --output-file``) and renders
a span tree using Rich.
"""

import json
import os
from datetime import datetime, timezone
from typing import Any

import click

from ._utils._console import ConsoleLogger
from ._utils._constants import TRACES_DIR
from ._utils._span_tree import (
    build_tree,
    filter_contains,
    filter_tree,
    render_tree,
)

console = ConsoleLogger()

# Sentinel returned by ``--trace-file`` when the flag is passed without a
# value.  The actual path is then generated by ``default_trace_path()``.
_TRACE_FILE_FLAG = "__auto__"


def default_trace_path(command: str) -> str:
    """Return a timestamped path under ``.uipath/traces/``.

    Args:
        command: The CLI command name (``"run"`` or ``"eval"``), used as a
            filename prefix so ``trace list`` output is easy to scan.

    Returns:
        A path like ``.uipath/traces/run_2026-04-07T14-58-30.jsonl``.
    """
    ts = datetime.now().strftime("%Y-%m-%dT%H-%M-%S")
    return os.path.join(TRACES_DIR, f"{command}_{ts}.jsonl")


def resolve_trace_file(trace_file: str | None, command: str) -> str | None:
    """Resolve *trace_file* from the CLI option to a concrete path.

    * ``None``        → tracing disabled (option not passed)
    * ``_TRACE_FILE_FLAG`` → generate a default path via :func:`default_trace_path`
    * anything else   → use as-is (explicit path from the user)
    """
    if trace_file is None:
        return None
    if trace_file == _TRACE_FILE_FLAG:
        return default_trace_path(command)
    return trace_file


# ---------------------------------------------------------------------------
# Span loading helpers
# ---------------------------------------------------------------------------


def _load_jsonl_spans(path: str) -> list[dict[str, Any]]:
    """Load spans from a JSONL trace file (one OTel span JSON per line)."""
    spans: list[dict[str, Any]] = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                spans.append(json.loads(line))
    return spans


def _load_eval_output_spans(path: str, eval_id: str | None) -> list[dict[str, Any]]:
    """Load spans from an eval verbose JSON output file.

    Returns JSONL-style span dicts (normalised from the
    ``TrajectoryEvaluationSpan`` format stored under
    ``agentExecutionOutput.trace.spans``).
    """
    with open(path, encoding="utf-8") as f:
        data = json.load(f)

    results: list[dict[str, Any]] = data.get("evaluationSetResults", [])

    all_spans: list[dict[str, Any]] = []
    for result in results:
        name = result.get("evaluationName", "")
        if eval_id is not None and name != eval_id:
            continue

        exec_output = result.get("agentExecutionOutput")
        if exec_output is None:
            continue

        trace_data = exec_output.get("trace", {})
        raw_spans = trace_data.get("spans", [])

        for sp in raw_spans:
            all_spans.append(_normalise_eval_span(sp, eval_name=name))

    return all_spans


def _normalise_eval_span(sp: dict[str, Any], eval_name: str) -> dict[str, Any]:
    """Convert a ``TrajectoryEvaluationSpan`` dict into the JSONL-like shape.

    The eval format stores ``parent_name`` instead of ``parent_id``, so we
    keep both representations so the tree builder can work with either.
    """
    return {
        "name": sp.get("name", ""),
        "status": {"status_code": (sp.get("status", "unset") or "unset").upper()},
        "attributes": sp.get("attributes", {}),
        "events": sp.get("events", []),
        # Eval-specific: no span IDs, only parent_name
        "parent_name": sp.get("parent_name"),
        "_eval_name": eval_name,
    }


# ---------------------------------------------------------------------------
# File-format detection
# ---------------------------------------------------------------------------


def _detect_format(path: str) -> str:
    """Return ``'jsonl'`` or ``'eval_json'`` based on file content."""
    if path.endswith(".jsonl"):
        return "jsonl"

    with open(path, encoding="utf-8") as f:
        first_char = f.read(1)

    if first_char == "[" or first_char == "{":
        # Peek inside to see if it looks like eval output
        with open(path, encoding="utf-8") as f:
            try:
                data = json.load(f)
            except json.JSONDecodeError:
                return "jsonl"

        if isinstance(data, dict) and "evaluationSetResults" in data:
            return "eval_json"

    return "jsonl"


# ---------------------------------------------------------------------------
# Click command group
# ---------------------------------------------------------------------------


@click.group(invoke_without_command=True)
@click.pass_context
def trace(ctx: click.Context) -> None:
    """Work with agent execution traces.

    \b
    Examples:
        uipath trace view traces.jsonl
        uipath trace view traces.jsonl --name "get_weather"
        uipath trace view traces.jsonl --contains "get_random*"
    """  # noqa: D301
    if ctx.invoked_subcommand is None:
        click.echo(ctx.get_help())


@trace.command()
@click.argument("file", type=click.Path(exists=True, dir_okay=False))
@click.option(
    "--name",
    default=None,
    help="Filter spans by name (glob pattern, e.g. 'agent*')",
)
@click.option(
    "--eval-id",
    default=None,
    help="Show trace for a specific evaluation by name (eval JSON only)",
)
@click.option(
    "--span-type",
    default=None,
    help="Filter by span_type attribute (e.g. 'TOOL', 'function_call_async')",
)
@click.option(
    "--status",
    default=None,
    type=click.Choice(["ok", "error", "unset"], case_sensitive=False),
    help="Filter by span status",
)
@click.option(
    "--contains",
    "contains_pattern",
    default=None,
    help="Show full subtrees containing a span matching this name (glob pattern)",
)
@click.option(
    "--no-input",
    is_flag=True,
    default=False,
    help="Hide input values",
)
@click.option(
    "--no-output",
    is_flag=True,
    default=False,
    help="Hide output values",
)
@click.option(
    "--full",
    is_flag=True,
    default=False,
    help="Show all span attributes (verbose mode)",
)
def view(
    file: str,
    name: str | None,
    eval_id: str | None,
    span_type: str | None,
    status: str | None,
    contains_pattern: str | None,
    no_input: bool,
    no_output: bool,
    full: bool,
) -> None:
    """Visualize an agent execution trace.

    \b
    Reads trace files produced by:
      - uipath run --trace-file <file.jsonl>
      - uipath eval --trace-file <file.jsonl>
      - uipath eval --verbose --output-file <file.json>

    \b
    Examples:
        uipath trace view traces.jsonl
        uipath trace view traces.jsonl --name "get_weather"
        uipath trace view traces.jsonl --span-type TOOL
        uipath trace view traces.jsonl --status error
        uipath trace view traces.jsonl --contains "get_random*"
        uipath trace view eval_output.json --eval-id "test-case-1"
        uipath trace view traces.jsonl --full
    """  # noqa: D301
    fmt = _detect_format(file)

    if fmt == "eval_json":
        spans = _load_eval_output_spans(file, eval_id)
        if not spans:
            if eval_id:
                console.error(
                    f"No traces found for evaluation '{eval_id}'. "
                    "Make sure the eval was run with --verbose."
                )
            else:
                console.error(
                    "No traces found in the eval output. "
                    "Make sure the eval was run with --verbose."
                )
        is_eval = True
    else:
        spans = _load_jsonl_spans(file)
        if not spans:
            console.error("No spans found in the trace file.")
        is_eval = False

    roots = build_tree(spans, is_eval=is_eval)

    # --contains: keep full subtrees that contain a matching span
    if contains_pattern:
        roots = filter_contains(roots, contains_pattern)

    # Apply filters
    roots = filter_tree(
        roots,
        name_pattern=name,
        span_type_filter=span_type,
        status_filter=status,
    )

    if not roots:
        from rich.console import Console as RichConsole

        RichConsole(force_terminal=True).print(
            "[yellow]No spans match the given filters.[/yellow]"
        )
        return

    render_tree(
        roots,
        show_input=not no_input,
        show_output=not no_output,
        show_full=full,
        max_value_length=0 if full else 200,
    )


# ---------------------------------------------------------------------------
# Trace file discovery
# ---------------------------------------------------------------------------

_OTEL_SPAN_KEYS = {"name", "context", "start_time", "end_time"}


def _is_otel_jsonl(path: str) -> bool:
    """Check whether *path* looks like an OTel JSONL trace file.

    Peeks at the first non-empty line and checks for characteristic
    OpenTelemetry span keys.
    """
    try:
        with open(path, encoding="utf-8") as f:
            for raw in f:
                line = raw.strip()
                if not line:
                    continue
                obj = json.loads(line)
                if isinstance(obj, dict) and _OTEL_SPAN_KEYS.issubset(obj):
                    return True
                return False
    except (json.JSONDecodeError, OSError, UnicodeDecodeError):
        pass
    return False


def _is_eval_json(path: str) -> bool:
    """Check whether *path* looks like eval verbose JSON output."""
    try:
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
        return isinstance(data, dict) and "evaluationSetResults" in data
    except (json.JSONDecodeError, OSError, UnicodeDecodeError):
        return False


def _count_spans_in_file(path: str, fmt: str) -> int:
    """Return the number of spans in a trace file."""
    try:
        if fmt == "jsonl":
            count = 0
            with open(path, encoding="utf-8") as f:
                for line in f:
                    if line.strip():
                        count += 1
            return count
        else:
            with open(path, encoding="utf-8") as f:
                data = json.load(f)
            total = 0
            for result in data.get("evaluationSetResults", []):
                exec_output = result.get("agentExecutionOutput")
                if exec_output is None:
                    continue
                spans = exec_output.get("trace", {}).get("spans", [])
                total += len(spans)
            return total
    except Exception:
        return 0


def _file_modified_time(path: str) -> datetime:
    """Return the last-modified time of *path* as a tz-aware datetime."""
    ts = os.path.getmtime(path)
    return datetime.fromtimestamp(ts, tz=timezone.utc)


def _discover_trace_files(root: str) -> list[dict[str, Any]]:
    """Walk *root* recursively and return metadata for every trace file found."""
    found: list[dict[str, Any]] = []

    for dirpath, _dirnames, filenames in os.walk(root):
        for fname in filenames:
            full = os.path.join(dirpath, fname)
            rel = os.path.relpath(full, root)

            if fname.endswith(".jsonl") and _is_otel_jsonl(full):
                found.append(
                    {
                        "path": rel,
                        "format": "jsonl",
                        "spans": _count_spans_in_file(full, "jsonl"),
                        "modified": _file_modified_time(full),
                        "size": os.path.getsize(full),
                    }
                )
            elif fname.endswith(".json") and _is_eval_json(full):
                found.append(
                    {
                        "path": rel,
                        "format": "eval_json",
                        "spans": _count_spans_in_file(full, "eval_json"),
                        "modified": _file_modified_time(full),
                        "size": os.path.getsize(full),
                    }
                )

    # Most recently modified first
    found.sort(key=lambda f: f["modified"], reverse=True)
    return found


def _human_size(nbytes: int) -> str:
    """Format *nbytes* as a human-readable string."""
    size: float = nbytes
    for unit in ("B", "KB", "MB", "GB"):
        if size < 1024:
            return f"{size:.0f}{unit}" if unit == "B" else f"{size:.1f}{unit}"
        size /= 1024
    return f"{size:.1f}TB"


# ---------------------------------------------------------------------------
# ``trace list`` subcommand
# ---------------------------------------------------------------------------


@trace.command(name="list")
@click.argument(
    "directory",
    default=None,
    required=False,
    type=click.Path(exists=True, file_okay=False),
)
def list_traces(directory: str | None) -> None:
    """Find and list trace files in a directory.

    \b
    Scans DIRECTORY recursively for trace files.  Defaults to
    .uipath/traces (where ``--trace-file`` writes by default).

    \b
    Recognised formats:
      - JSONL trace files from ``uipath run --trace-file``
      - JSONL trace files from ``uipath eval --trace-file``
      - JSON eval output from ``uipath eval --verbose --output-file``

    \b
    Examples:
        uipath trace list
        uipath trace list .uipath/traces
        uipath trace list ./experiments
    """  # noqa: D301
    from rich.console import Console
    from rich.table import Table

    rich_console = Console(force_terminal=True)

    if directory is None:
        directory = TRACES_DIR

    if not os.path.isdir(directory):
        rich_console.print(
            f"[yellow]Trace directory [bold]{directory}[/bold] does not exist. "
            "Run with [bold]--trace-file[/bold] to generate traces.[/yellow]"
        )
        return

    root = os.path.abspath(directory)
    files = _discover_trace_files(root)

    if not files:
        rich_console.print(f"[yellow]No trace files found in {directory}[/yellow]")
        return

    table = Table(title=f"Trace files in [bold]{directory}[/bold]")
    table.add_column("File", style="cyan", no_wrap=True)
    table.add_column("Format", style="dim")
    table.add_column("Spans", justify="right")
    table.add_column("Size", justify="right", style="dim")
    table.add_column("Modified", style="dim")

    now = datetime.now(tz=timezone.utc)
    for f in files:
        age = now - f["modified"]
        if age.total_seconds() < 60:
            when = "just now"
        elif age.total_seconds() < 3600:
            mins = int(age.total_seconds() // 60)
            when = f"{mins}m ago"
        elif age.total_seconds() < 86400:
            hours = int(age.total_seconds() // 3600)
            when = f"{hours}h ago"
        else:
            when = f["modified"].strftime("%Y-%m-%d %H:%M")

        fmt_label = "JSONL" if f["format"] == "jsonl" else "eval JSON"
        table.add_row(
            f["path"],
            fmt_label,
            str(f["spans"]),
            _human_size(f["size"]),
            when,
        )

    rich_console.print(table)
    rich_console.print(
        "\n[dim]Tip: run [bold]uipath trace view <file>[/bold] "
        "to visualize a trace[/dim]"
    )
