name: CD

on:
  push:
    branches:
      - main
    paths:
      - pyproject.toml

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml

  build:
    needs: [lint, test]
    uses: ./.github/workflows/build.yml
    secrets:
      token: ${{ secrets.PYPI_TOKEN }}
      repo_access: ${{ secrets.REPO_ACCESS }}