name: Core CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - "src/uipath_sdk/**"
  pull_request:
    branches:
      - main
    paths:
      - "src/uipath_sdk/**"

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml
