name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  commit-lint:
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/commitlint.yml

  lint:
    uses: ./.github/workflows/lint-packages.yml

  test:
    uses: ./.github/workflows/test-packages.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  check-versions:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/check-version-availability.yml

  check-dependency-bumps:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/check-dependency-bumps.yml
