name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - 'packages/uipath_sdk/**'
  pull_request:
    branches:
      - main
    paths:
      - 'packages/uipath_sdk/**'

jobs:
  lint:
    name: Static Checks
    runs-on: "ubuntu-24.04"
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5

      - uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'

      - name: Prepare setup
        working-directory: packages/uipath_sdk
        run: |
            cp ../../README.md .

      - name: Setup venv
        working-directory: packages/uipath_sdk
        run: |
          uv venv
          uv sync --all-extras

      - name: "Check static types"
        working-directory: packages/uipath_sdk
        run: |
          uv run mypy --config-file pyproject.toml .

      - name: "Check linting"
        working-directory: packages/uipath_sdk
        run: |
          uv run ruff check .

      - name: "Check formatting"
        working-directory: packages/uipath_sdk
        run: |
          uv run ruff format --check .

  build:
    name: Build and publish
    needs: [lint]
    if: github.ref == 'refs/heads/main'
    runs-on: "ubuntu-24.04"
    steps:
      - uses: actions/checkout@v4
      
      - uses: astral-sh/setup-uv@v5

      - uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'

      - name: Setup venv
        working-directory: packages/uipath_sdk
        run: |
          uv venv
          uv sync --all-extras

      - name: Build
        working-directory: packages/uipath_sdk
        run: |
          uv build

      - name: "Publish"
        working-directory: packages/uipath_sdk
        run: |
          uv publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}