name: Core CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - "sdk/core/**"
  pull_request:
    branches:
      - main
    paths:
      - "sdk/core/**"

defaults:
  run:
    working-directory: "sdk/core"

jobs:
  lint:
    name: Static Checks
    runs-on: "ubuntu-24.04"
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5

      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Setup venv
        run: |
          uv venv
          uv sync --all-extras

      - name: "Check static types"
        run: |
          uv run mypy --config-file pyproject.toml .

      - name: "Check linting"
        run: |
          uv run ruff check .

      - name: "Check formatting"
        run: |
          uv run ruff format --check .

  test:
    name: Tests
    runs-on: "ubuntu-24.04"
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5

      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: "Setup venv"
        run: |
          uv venv
          uv sync --all-extras

      - name: "Run tests"
        run: |
          uv run pytest

  build:
    needs: [lint, test]
    uses: ./.github/workflows/build.yml
    with:
      folder_path: "sdk/core"
    secrets:
      token: ${{ secrets.PYPI_TOKEN }}
