name: Langchain CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - "sdk/langchain/**"
  pull_request:
    branches:
      - main
    paths:
      - "sdk/langchain/**"

jobs:
  lint:
    name: Static Checks
    runs-on: "ubuntu-24.04"
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5

      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Setup venv
        working-directory: sdk/langchain
        run: |
          uv venv
          uv sync --all-extras

      - name: "Check static types"
        working-directory: sdk/langchain
        run: |
          uv run mypy --config-file pyproject.toml .

      - name: "Check linting"
        working-directory: sdk/langchain
        run: |
          uv run ruff check .

      - name: "Check formatting"
        working-directory: sdk/langchain
        run: |
          uv run ruff format --check .

  build:
    name: Build and publish
    needs: [lint]
    if: github.ref == 'refs/heads/main'
    runs-on: "ubuntu-24.04"
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5

      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Setup venv
        working-directory: sdk/langchain
        run: |
          uv venv
          uv sync --all-extras

      - name: Build
        working-directory: sdk/langchain
        run: |
          uv build

      - name: "Publish"
        working-directory: sdk/langchain

        run: |
          uv publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
