name: Publish Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "packages/uipath/docs/**"
      - "packages/uipath/mkdocs.yml"
      - "packages/uipath/pyproject.toml"
      - "packages/uipath-platform/src/**"
      - "packages/uipath-platform/pyproject.toml"
      - "packages/uipath-core/src/**"
      - "packages/uipath-core/pyproject.toml"
  repository_dispatch:
    types: [publish-docs]

jobs:
  publish-docs:
    runs-on: uipath-ubuntu-latest
    if: ${{ github.repository == 'UiPath/uipath-python' }}
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4.4.0

      - name: Setup uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86  # v5.4.2
        with:
          enable-cache: true

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
        with:
          python-version-file: "packages/uipath/.python-version"

      - name: Install dependencies
        working-directory: packages/uipath
        run: uv sync --all-extras

      - name: Clone plugins
        run: |
          git clone https://x-access-token:${{ secrets.REPO_ACCESS }}@github.com/UiPath/uipath-langchain-python plugins/uipath-langchain-python
          git clone https://x-access-token:${{ secrets.REPO_ACCESS }}@github.com/UiPath/uipath-integrations-python plugins/uipath-integrations-python
          git clone https://x-access-token:${{ secrets.REPO_ACCESS }}@github.com/UiPath/uipath-mcp-python plugins/uipath-mcp-python

      - name: Symlink plugin docs
        working-directory: packages/uipath
        run: |
          ln -s ../../../plugins/uipath-langchain-python/docs docs/langchain
          ln -s ../../../plugins/uipath-integrations-python/packages/uipath-llamaindex/docs docs/llamaindex
          ln -s ../../../plugins/uipath-integrations-python/packages/uipath-openai-agents/docs docs/openai-agents
          ln -s ../../../plugins/uipath-mcp-python/docs docs/mcp
          ls -a docs/langchain
          ls -a docs/llamaindex
          ls -a docs/openai-agents
          ls -a docs/mcp

      - name: Publish Docs
        working-directory: packages/uipath
        run: uv run mkdocs gh-deploy --force
