name: Dumb CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths-ignore:
      - "src/**"
      - "pyproject.toml"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "src/**"
      - "pyproject.toml"

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      should_skip: true

  test:
    uses: ./.github/workflows/test.yml
    with:
      should_skip: true