name: Reusable Test Workflow

on:
  workflow_call:
    inputs:
    
      folder_path:
        description: 'The folder path to run actions in'
        required: true
        type: string
      should_skip:
          description: 'Whether to skip the linting step'
          required: false
          type: boolean
          default: false

jobs:
  test:
    name: Test
    runs-on: "ubuntu-24.04"
    environment: PYPY_TOKEN
    if: inputs.should_skip == false
    defaults:
      run:
        working-directory: ${{ inputs.folder_path }}

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5

      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: "Setup venv"
        run: |
          uv venv
          uv sync --all-extras

      - name: "Run tests"
        run: |
          printenv | sort
          uv run pytest
        env:
          UIPATH_URL: ${{ secrets.UIPATH_URL }}
          UIPATH_CLIENT_ID: ${{ secrets.UIPATH_CLIENT_ID }}
          UIPATH_CLIENT_SECRET: ${{ secrets.UIPATH_CLIENT_SECRET }}
          UIPATH_ORGANIZATION_ID: ${{ vars.UIPATH_ORGANIZATION_ID }}
          UIPATH_TENANT_ID: ${{ vars.UIPATH_TENANT_ID }}

