name: Test UiPath Langchain

on:
  pull_request:
    types: [ opened, synchronize, reopened, labeled ]

jobs:
  test-uipath-langchain:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13" ]
        os: [ ubuntu-latest, windows-latest ]

    permissions:
      contents: read

    # Only run if PR has the test:uipath-langchain label
    if: contains(github.event.pull_request.labels.*.name, 'test:uipath-langchain')

    steps:
      - name: Checkout uipath-python
        uses: actions/checkout@v4
        with:
          path: 'uipath-python'

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build uipath-python package
        run: |
          cd uipath-python
          uv build

      - name: Checkout uipath-langchain-python
        uses: actions/checkout@v4
        with:
          repository: 'UiPath/uipath-langchain-python'
          path: 'uipath-langchain-python'
          token: ${{ secrets.REPO_ACCESS }}

      - name: Update uipath-python version
        shell: bash
        run: |
          cd uipath-langchain-python
          uv add ../uipath-python/dist/*.whl --dev

      - name: Run uipath-langchain tests
        run: |
          cd uipath-langchain-python
          uv sync
          uv run pytest


